apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-app
  labels:
    app: awesome-app
    backstage.io/kubernetes-id: awesome-app  # 🔹 Backstage Integration Label
spec:
  replicas: 2  # Running 2 instances (pods)
  selector:
    matchLabels:
      app: awesome-app
  template:
    metadata:
      labels:
        app: awesome-app
    spec:
      containers:
        - name: awesome-app
          image: nginx:latest  # Using Nginx as a sample app
          ports:
            - containerPort: 80  # Exposing port 80

---
apiVersion: v1
kind: Service
metadata:
  name: awesome-app-service
  labels:
    app: awesome-app
spec:
  type: NodePort  # Exposes service on a port accessible from the host
  selector:
    app: awesome-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081  # External port (accessible from the host)

